# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 小刀的博客
email: pengyao_2@163.com
description: > # this means to ignore newlines until "baseurl:"
  欢迎来到我的博客.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://young-peng.github.io/" # the base hostname & protocol for your site
linkedin_username: 瑶-彭-15bb66108
github_username:  young-peng
blog_url: "/blog"

avatar: yes
#avatar_img_path: "imgs/avatar.jpg""
# You can link to your GitHub image. That way it will get updated
# automatically whenever you change your GitHub profile picture
avatar_img_path: "https://avatars3.githubusercontent.com/u/5433835?v=3&s=460"

port: 5000

front_img: yes
front_img_path: "imgs/background.jpg"

about_footer: false

favicon_img: yes
favicon_img_path: "imgs/favicon.ico"

# defaults:
#     -
#         scope:
#             path:   ""
#             type:   "blog"
#         values:
#             layout: "page"
#     -

